print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? "))
tip_percent = int(input("What percentage tip would you like to give? 10, 12 or 15? "))
people_count = int(input("How many people to split the bill? "))
tip_per_person = (total_bill / people_count) + ((tip_percent / 100) * (total_bill / people_count))
print(f"Each person should pay: {round(tip_per_person, 2)}")
